# R for travis     : see documentation at https://docs.travis-ci.com/user/languages/r
# Python reference : GeoMongo, scaffolder

language: R
sudo: true
cache: packages

os:
  - linux

python:
  - 3.5   

before_install:
  - sudo apt-get install python3-pip
  - sudo pip3 install --upgrade pip
  - sudo python3 -m pip install --upgrade --ignore-installed numpy cython matplotlib POT
  - sudo apt-get install r-base-dev
  - sudo apt-get update

addons:
  apt:
    packages:
      - cmake
      - glpk-utils
      - libmpfr-dev
      - xorg
      - libx11-dev
      - libglu1-mesa-dev
      - libfreetype6-dev
      - libgdal-dev 
      - libgeos-dev 
      - gdal-bin 
      - proj-bin
      - libproj-dev
      - cargo
      - libstd-rust-dev
      - rust-gdb
      - rustc

r:
  - release

r-packages:
  - Rcpp
  - RcppArmadillo
  - Rdpack
  - stats
  - utils
  - ggplot2
  - knitr
  - lpSolve
  - reticulate
  - rmarkdown

env:
  global:
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --ignore-vignettes --no-examples"
    - R_BUILD_ARGS="--no-build-vignettes"
    - RGL_USE_NULL=TRUE

warnings_are_errors: false
